AllCops:
  # Set the Ruby version you are targeting:
  TargetRubyVersion: 3.2.2

  # Exclude files that shouldn't be inspected
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

# Limit lines to a readable length.
Layout/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*'  # Allow longer lines in specs

# Recommend {} for single-line blocks & do..end for multi-line blocks.
Style/BlockDelimiters:
  EnforcedStyle: line_count_based

# Use double quotes for strings.
#tyle/StringLiterals:
#  EnforcedStyle: double_quotes

# Documentation comments are not required.
Style/Documentation:
  Enabled: false

# Avoid single-character variable names.
Naming/MethodParameterName:
  MinNameLength: 2

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

# Avoid using the `for` keyword, prefer `each`.
Style/For:
  Enabled: true

# Prefer `&&` and `||` over `and` and `or`.
Style/AndOr:
  EnforcedStyle: conditionals
